name = "communication-service"
main = "src/index.ts"
compatibility_date = "2024-10-23"
#compatibility_flags = ["nodejs_compat"]
node_compat = true
workers_dev = true

[vars]
SENDGRID_API_KEY = "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"
SENDGRID_URL="https://api.sendgrid.com/v3/mail/send"
SG_API_KEY="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"

INTERVIEW_SUPPORT_EMAIL="interview-support@dashflowx.com"
SUPPORT_EMAIL="support@dashflowx.com"

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1