name = "communication-service"
main = "src/index.ts"
compatibility_date = "2024-10-23"
#compatibility_flags = ["nodejs_compat"]
node_compat = true
workers_dev = true

[vars]
SENDGRID_API_KEY = "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"
SENDGRID_URL="https://api.sendgrid.com/v3/mail/send"
SG_API_KEY="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"

INTERVIEW_SUPPORT_EMAIL="interview-support@hireomatic.com"
SUPPORT_EMAIL="support@hireomatic.com"

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1